### ISSUE TITLE
New contribution: Magicoder

### ISSUE THREAD

**Issue by UniverseFly** [deepseek-ai/awesome-deepseek-coder#1]
Thanks for the great work!! Our recent work [Magicoder](https://github.com/ise-uiuc/magicoder) also builds upon [deepseek-coder-6.7b-base](https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base), specifically for the following two variants:

- [Magicoder-DS-6.7B](https://huggingface.co/ise-uiuc/Magicoder-DS-6.7B)
- [Magicoder-*S*-DS-6.7B](https://huggingface.co/ise-uiuc/Magicoder-S-DS-6.7B)

Maybe it can be added to this repo!

**Comment by luofuli** [comment]
Thx. We have added to our repo. 

> Thanks for the great work!! Our recent work [Magicoder](https://github.com/ise-uiuc/magicoder) also builds upon [deepseek-coder-6.7b-base](https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base), specifically for the following two variants:
> 
> * [Magicoder-DS-6.7B](https://huggingface.co/ise-uiuc/Magicoder-DS-6.7B)
> * [Magicoder-_S_-DS-6.7B](https://huggingface.co/ise-uiuc/Magicoder-S-DS-6.7B)
> 
> Maybe it can be added to this repo!
